// Generated by CoffeeScript 1.3.3
(function() {
  var $jq;

  alert("Coffee");

  $jq = $.get("http://www.tvblog.ro", function(response) {
    var $headlines, $value, value, _i, _len, _results;
    $headlines = $("#content h2 a", response);
    _results = [];
    for (_i = 0, _len = $headlines.length; _i < _len; _i++) {
      value = $headlines[_i];
      $value = $(value);
      _results.push($(document).find("body").append($("<p><a target='_blank' href='" + $value.attr("href") + "'>" + $value.html() + "</a></p>")));
    }
    return _results;
  });

  $jq.error(function(jqXHR, textStatus, errorThrown) {
    return alert("There was an error...sorry!");
  });

}).call(this);
